name: Build ZIP on merge to main

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  build-zip:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    env:
      PLUGIN_SLUG: fp-restaurant-reservations
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Install composer deps (no dev)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          composer dump-autoload -o --classmap-authoritative

      - name: Ensure tools present
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync zip

      - name: Package plugin
        run: |
          set -e
          OUTDIR=build/${PLUGIN_SLUG}
          rm -rf build && mkdir -p "$OUTDIR"
          rsync -a ./ "$OUTDIR" \
            --exclude ".git/" --exclude ".github/" --exclude "node_modules/" \
            --exclude "tests/" --exclude "docs/" --exclude "build/" \
            --exclude "scripts/" --exclude ".gitignore" --exclude "*.zip" \
            --exclude "*.log" --exclude "AUDIT/" --exclude "AUDIT.md" \
            --exclude "phpstan.neon" --exclude "phpcs.xml"
          (cd build && zip -r "${PLUGIN_SLUG}.zip" "${PLUGIN_SLUG}")
          echo "ZIP creato: build/${PLUGIN_SLUG}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_SLUG }}
          path: build/*.zip
          if-no-files-found: error
