name: Build plugin ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLUGIN_SLUG: fp-restaurant-reservations
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          composer dump-autoload -o --classmap-authoritative

      - name: Prepare build directory
        run: |
          mkdir -p build/${PLUGIN_SLUG}
          rsync -a --delete \
            --exclude=.git \
            --exclude=.github \
            --exclude=tests \
            --exclude=docs \
            --exclude=node_modules \
            --exclude=*.md \
            --exclude=.idea \
            --exclude=.vscode \
            --exclude=build \
            --exclude=.gitattributes \
            --exclude=.gitignore \
            --exclude=package.json \
            --exclude=package-lock.json \
            --exclude=phpcs.xml \
            --exclude=phpstan.neon \
            --exclude=vite.config.js \
            --exclude=.codex-state.json \
            --exclude=.rebuild-state.json \
            --exclude=.eslintrc.cjs \
            --exclude=.prettierrc.json \
            --exclude=build.sh \
            --exclude=scripts \
            ./ build/${PLUGIN_SLUG}/

      - name: Create ZIP
        run: |
          cd build
          zip -r ${PLUGIN_SLUG}.zip ${PLUGIN_SLUG}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: build/${PLUGIN_SLUG}.zip
