name: Build WP Plugin ZIP

on:
  workflow_dispatch: {}           # avvio manuale dal tab "Actions"
  push:
    branches:
      - main                      # parte su push in main
    tags:
      - 'v*'                      # parte su push di tag v1.2.3 ecc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install composer deps (no dev)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          composer dump-autoload -o --classmap-authoritative

      - name: Ensure tools present
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync zip

      # Se hai build.sh nel repo, lo usiamo; altrimenti pack "inline".
      - name: Make build.sh executable (if present)
        run: |
          if [ -f build.sh ]; then
            chmod +x build.sh
          fi

      - name: Run build.sh (if present)
        run: |
          if [ -f build.sh ]; then
            ./build.sh --bump=patch || bash build.sh --bump=patch
          fi

      - name: Package plugin (fallback inline)
        if: ${{ !hashFiles('build.sh') }}
        run: |
          set -e
          SLUG="$(basename "$GITHUB_WORKSPACE")"
          mkdir -p build/${SLUG}
          rsync -a ./ build/${SLUG} \
            --exclude ".git" --exclude ".github" --exclude ".gitignore" \
            --exclude "build" --exclude "tests" --exclude "docs" \
            --exclude "node_modules" --exclude ".idea" --exclude ".vscode" \
            --exclude "*.md" --exclude ".gitattributes"
          cd build
          zip -r "${SLUG}.zip" "${SLUG}"
          echo "ZIP creato in build/${SLUG}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: build/*.zip
