name: Release ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer:v2

      - name: Install composer deps (no dev)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          composer dump-autoload -o --classmap-authoritative

      - name: Ensure tools present
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync zip

      - name: Make build.sh executable (if present)
        run: |
          if [ -f build.sh ]; then
            chmod +x build.sh
          fi

      - name: Run build.sh (if present)
        run: |
          if [ -f build.sh ]; then
            ./build.sh --set-version=${GITHUB_REF_NAME#v}
          fi

      - name: Package plugin (fallback inline)
        if: ${{ !hashFiles('build.sh') }}
        run: |
          set -e
          SLUG=fp-restaurant-reservations
          OUTDIR=build/${SLUG}
          rm -rf build && mkdir -p "$OUTDIR"
          rsync -a ./ "$OUTDIR" \
            --exclude ".git/" --exclude ".github/" --exclude "node_modules/" \
            --exclude "tests/" --exclude "docs/" --exclude "build/" \
            --exclude "scripts/" --exclude ".gitignore" --exclude "*.zip" \
            --exclude "*.log" --exclude "AUDIT/" --exclude "AUDIT.md"
          (cd build && zip -r "${SLUG}.zip" "${SLUG}")
          echo "ZIP creato: build/${SLUG}.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: build/*.zip

      - name: Publish GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


